# Default values for masterportal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

projectname: ""

defaultPodSecurityContext: &defaultPodSecurityContext
  runAsNonRoot: true
  runAsUser: 65533
  runAsGroup: 65533
  fsGroup: 65533

defaultSecurityContext: &defaultSecurityContext
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true

nameOverride: ""
fullnameOverride: ""

masterportal:
  image:
    registry: docker.io
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets: []

  podSecurityContext: *defaultPodSecurityContext
  securityContext: *defaultSecurityContext

  replicas: 1
  
  ports:
    http:
      servicePort: 80
      targetPort: 8080

  ingress:
    enabled: true
    annotations:
    host: ""
    tls:
      enabled: false
      secretName: []

  sidecar:
    enabled: true
    image:
      registry: k8s.gcr.io/git-sync
      repository: git-sync
      tag: v3.6.5
      pullPolicy: IfNotPresent
      pullSecrets: []

    git:
      repository: https://github.com/myuser/myapp.git
      branch: main
      path: /git
      gitSecret: []

  resources:
    requests:
      cpu: 100m
      memory: 128Mi