{{- $fullname := include "masterportal.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "masterportal.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "masterportal.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.masterportal.replicas }}
  template:
    metadata:
      labels:
        {{- include "masterportal.selectorLabels" . | nindent 8 }}}
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.masterportal.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $fullname }}
          image: "{{ .Values.masterportal.image.registry }}/{{ .Values.masterportal.image.repository }}:{{ .Values.masterportal.image.tag }}"
          imagePullPolicy: {{ .Values.masterportal.image.pullPolicy | quote }}
          {{- with .Values.masterportal.image.pullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.masterportal.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 80
          resources:
            {{- toYaml .Values.masterportal.resources | nindent 12 }}
          {{- if .Values.masterportal.sidecar.enabled }}
        - name: git-sync
          image: "{{ .Values.masterportal.sidecar.image.registry }}/{{ .Values.masterportal.sidecar.image.repository }}:{{ .Values.masterportal.sidecar.image.tag }}"
          imagePullPolicy: {{ .Values.masterportal.image.pullPolicy | quote }}
          {{- with .Values.masterportal.sidecar.image.pullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.masterportal.securityContext | nindent 12 }}
          args:
            - "--repo={{ .Values.masterportal.sidecar.git.repository }}"
            - "--branch={{ .Values.masterportal.sidecar.git.branch }}"
            - "--root={{ .Values.masterportal.sidecar.git.path }}"
            - "--ssh"
            - "--dest=html"
            - "--wait=10"
          volumeMounts:
            - name: git-secret
              mountPath: /etc/git-secret
              readOnly: true
            - name: git-config
              mountPath: "/git"
              readOnly: false
        {{- end }}
      volumes:
        - name: git-secret
          secret:
            secretName: {{ $fullname }}-git-secret
            defaultMode: 0400
        - name: git-config
          emptyDir: {}