{{- if .Values.masterportal.sidecar.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "masterportal.fullName" . }}-gitSecret
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "masterportal.chart" . }}
    app: {{ include "masterportal.name" . }}
data:
  known_hosts: {{ .Values.masterportal.sidecar.gitSecret.knownHosts }}
  ssh: {{ .Values.masterportal.sidecar.gitSecret.sshKey }}
{{ end }}