{{- if .Values.masterportal.ingress.enabled -}}
{{- $fullName := include "masterportal.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    {{- range $key, $value := .Values.masterportal.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    {{- include "masterportal.labels" . | nindent 4 }}
spec:
  {{- if .Values.masterportal.ingress.ingressClassName }}
  ingressClassName: {{ .Values.masterportal.ingress.ingressClassName }}
  {{- end -}}
  {{- if .Values.masterportal.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.masterportal.ingress.serviceHost }}
    {{- if .Values.masterportal.ingress.tls.secretName }}
      secretName: {{ .Values.masterportal.ingress.tls.secretName }}
    {{- end -}}
  {{- end }}
  rules:
  - host: {{ .Values.masterportal.serviceHost }}
    http:
      paths:
      - path:  {{ .Values.masterportal.ingress.path  }}
        pathType: Prefix
        backend:
          service:
            name:  {{ $fullName }}
            port:
              number: 80
{{- end -}}