{{- if .Values.masterportal.ingress.enabled -}}
{{- $fullName := include "masterportal.fullName" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    {{ .Values.masterportal.ingress.appRootAnnotation}}: {{ .Values.masterportal.ingress.appRootTraget}}
    {{- if .Values.masterportal.ingress.annotations }}
    {{- toYaml .Values.masterportal.ingress.annotations}}
    {{ end }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "masterportal.chart" . }}
    app: {{ include "masterportal.name" . }}
spec:
  {{- if .Values.masterportal.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.masterportal.ingress.host }}
    {{- if .Values.masterportal.ingress.tls.secretName }}
      secretName: {{ .Values.masterportal.ingress.tls.secretName }}
    {{- end -}}
  {{- end }}
  rules:
  - host: {{ .Values.masterportal.serviceHost }}
    http:
      paths:
      - path:  {{ .Values.masterportal.ingress.path  }}
        pathType: Prefix
        backend:
          service:
            name:  {{ $fullName }}
            port:
              number: 80
{{- end -}}