{{- $fullName := include "masterportal.fullname" . -}}
apiVersion: v1 
kind: ConfigMap
metadata:
  name: {{ $fullName }}-nginx-conf
data: 
  nginx.conf: |
    worker_processes  auto;

    error_log  /tmp/nginx/error.log warn;
    pid        /tmp/nginx/nginx.pid;

    events { 
      worker_connections  1024; 
    }

    http { 
      server {
        listen 8080; # specify a port higher than 1024 if running as non-root user 
        location / { 
          root  /usr/share/nginx/html/{{.Values.projectname}};
          include  /etc/nginx/mime.types;
        } 
      }
    }