{{- $fullname := include "masterportal.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "masterportal.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "masterportal.selectorLabels" . | nindent 4 }}
  {{- if not .Values.masterportal.ingress.enabled }}
  type: NodePort
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.masterportal.ports.http.servicePort }}
      {{- if not .Values.masterportal.ingress.enabled }}
      nodePort: {{ .Values.masterportal.ports.http.nodePort }}
      {{- end }}
      targetPort: http
